FROM ubuntu:23.04

# Install utils
RUN apt update
RUN apt install -y wget
RUN apt install -y dpkg

# Prepare to install Net sdk
RUN wget https://packages.microsoft.com/config/ubuntu/23.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb

# Install Net sdk
RUN apt install -y dotnet-sdk-7.0

# Install git
RUN apt install -y git

# Install more utils
RUN apt install -y gpg

# Install LiquiBase
RUN bash -c "wget -qO- https://repo.liquibase.com/liquibase.asc | gpg --dearmor > liquibase-keyring.gpg"
RUN bash -c "cat liquibase-keyring.gpg | tee /usr/share/keyrings/liquibase-keyring.gpg > /dev/null" 
RUN cat /dev/null > liquibase-keyring.gpg
RUN rm liquibase-keyring.gpg
RUN echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/liquibase-keyring.gpg] https://repo.liquibase.com stable main' | tee /etc/apt/sources.list.d/liquibase.list
RUN apt update
# installing specific liquibase version to avoid problems of new version 
RUN apt install -y liquibase=4.24.0 

# Install JDK
RUN wget https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb -O jdk-21_linux-x64_bin.deb
RUN dpkg -i jdk-21_linux-x64_bin.deb
RUN rm jdk-21_linux-x64_bin.deb

# Install sqlite3
RUN apt install sqlite3